controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - neck_y_joint
      - neck_p_joint
      - neck_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

waist_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - waist_y_joint
      - waist_p_joint
      - waist_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

rarm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - r_shoulder_p_joint
      - r_shoulder_r_joint
      - r_shoulder_y_joint
      - r_elbow_joint
      - r_wrist_y_joint
      - r_wrist_p_joint
      - r_wrist_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

larm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l_shoulder_p_joint
      - l_shoulder_r_joint
      - l_shoulder_y_joint
      - l_elbow_joint
      - l_wrist_y_joint
      - l_wrist_p_joint
      - l_wrist_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

lifter_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - knee_joint
      - ankle_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

lhand_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - l_thumb_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

rhand_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - r_thumb_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
